export type nationalityProp = {
  name: string;
  code: string;
};

const nationalities: nationalityProp[] = [
  { name: "Cambodian", code: "KH" },
  { name: "Chinese", code: "CN" },
  { name: "Malaysian", code: "MY" },
  { name: "Argentinian", code: "AR" },
  { name: "Afghan", code: "AF" },
  { name: "Albanian", code: "AL" },
  { name: "Algerian", code: "DZ" },
  { name: "American Samoan", code: "AS" },
  { name: "Andorran", code: "AD" },
  { name: "Angolan", code: "AO" },
  { name: "Anguillan", code: "AI" },
  { name: "Antarctic", code: "AQ" },
  { name: "Antiguan and Barbudan", code: "AG" },
  { name: "Armenian", code: "AM" },
  { name: "Aruban", code: "AW" },
  { name: "Australian", code: "AU" },
  { name: "Austrian", code: "AT" },
  { name: "Azerbaijani", code: "AZ" },
  { name: "Bahamian", code: "BS" },
  { name: "Bahraini", code: "BH" },
  { name: "Bangladeshi", code: "BD" },
  { name: "Barbadian", code: "BB" },
  { name: "Belarusian", code: "BY" },
  { name: "Belgian", code: "BE" },
  { name: "Belizean", code: "BZ" },
  { name: "Beninese", code: "BJ" },
  { name: "Bermudian", code: "BM" },
  { name: "Bhutanese", code: "BT" },
  { name: "Bolivian", code: "BO" },
  { name: "Bosnian", code: "BA" }, // (or "Bosnian and Herzegovinian")
  { name: "Botswanan", code: "BW" },
  { name: "Bouvet Islander", code: "BV" },
  { name: "Brazilian", code: "BR" },
  { name: "British", code: "IO" }, // for British Indian Ocean Territory
  { name: "Bruneian", code: "BN" },
  { name: "Bulgarian", code: "BG" },
  { name: "Burkinabé", code: "BF" },
  { name: "Burundian", code: "BI" },
  { name: "Cameroonian", code: "CM" },
  { name: "Canadian", code: "CA" },
  { name: "Cape Verdean", code: "CV" },
  { name: "Caymanian", code: "KY" },
  { name: "Central African", code: "CF" },
  { name: "Chadian", code: "TD" },
  { name: "Chilean", code: "CL" },
  { name: "Christmas Islander", code: "CX" },
  { name: "Cocos Islander", code: "CC" },
  { name: "Colombian", code: "CO" },
  { name: "Comorian", code: "KM" },
  { name: "Congolese", code: "CG" },
  { name: "Congolese", code: "CD" },
  { name: "Cook Islander", code: "CK" },
  { name: "Costa Rican", code: "CR" },
  { name: "Ivorian", code: "CI" },
  { name: "Croatian", code: "HR" },
  { name: "Cuban", code: "CU" },
  { name: "Cypriot", code: "CY" },
  { name: "Czech", code: "CZ" },
  { name: "Danish", code: "DK" },
  { name: "Djiboutian", code: "DJ" },
  { name: "Dominican", code: "DM" },
  { name: "Dominican", code: "DO" },
  { name: "Ecuadorian", code: "EC" },
  { name: "Egyptian", code: "EG" },
  { name: "Salvadoran", code: "SV" },
  { name: "Equatoguinean", code: "GQ" },
  { name: "Eritrean", code: "ER" },
  { name: "Estonian", code: "EE" },
  { name: "Ethiopian", code: "ET" },
  { name: "Falkland Islander", code: "FK" },
  { name: "Faroese", code: "FO" },
  { name: "Fijian", code: "FJ" },
  { name: "Finnish", code: "FI" },
  { name: "French", code: "FR" },
  { name: "French Guianese", code: "GF" },
  { name: "French Polynesian", code: "PF" },
  { name: "French", code: "TF" }, // French Southern Territories
  { name: "Gabonese", code: "GA" },
  { name: "Gambian", code: "GM" },
  { name: "Georgian", code: "GE" },
  { name: "German", code: "DE" },
  { name: "Ghanaian", code: "GH" },
  { name: "Gibraltarian", code: "GI" },
  { name: "Greek", code: "GR" },
  { name: "Greenlandic", code: "GL" },
  { name: "Grenadian", code: "GD" },
  { name: "Guadeloupean", code: "GP" },
  { name: "Guamanian", code: "GU" },
  { name: "Guatemalan", code: "GT" },
  { name: "Guernsey", code: "GG" },
  { name: "Guinean", code: "GN" },
  { name: "Bissau-Guinean", code: "GW" },
  { name: "Guyanese", code: "GY" },
  { name: "Haitian", code: "HT" },
  { name: "Heard Island and McDonald Islands", code: "HM" },
  { name: "Vatican", code: "VA" },
  { name: "Honduran", code: "HN" },
  { name: "Hong Kongese", code: "HK" },
  { name: "Hungarian", code: "HU" },
  { name: "Icelandic", code: "IS" },
  { name: "Indian", code: "IN" },
  { name: "Indonesian", code: "ID" },
  { name: "Iranian", code: "IR" },
  { name: "Iraqi", code: "IQ" },
  { name: "Irish", code: "IE" },
  { name: "Manx", code: "IM" },
  { name: "Israeli", code: "IL" },
  { name: "Italian", code: "IT" },
  { name: "Jamaican", code: "JM" },
  { name: "Japanese", code: "JP" },
  { name: "Jerseyan", code: "JE" },
  { name: "Jordanian", code: "JO" },
  { name: "Kazakhstani", code: "KZ" },
  { name: "Kenyan", code: "KE" },
  { name: "I-Kiribati", code: "KI" },
  { name: "North Korean", code: "KP" },
  { name: "South Korean", code: "KR" },
  { name: "Kuwaiti", code: "KW" },
  { name: "Kyrgyz", code: "KG" },
  { name: "Laotian", code: "LA" },
  { name: "Latvian", code: "LV" },
  { name: "Lebanese", code: "LB" },
  { name: "Basotho", code: "LS" },
  { name: "Liberian", code: "LR" },
  { name: "Libyan", code: "LY" },
  { name: "Liechtensteiner", code: "LI" },
  { name: "Lithuanian", code: "LT" },
  { name: "Luxembourgish", code: "LU" },
  { name: "Macanese", code: "MO" },
  { name: "Macedonian", code: "MK" },
  { name: "Malagasy", code: "MG" },
  { name: "Malawian", code: "MW" },
  { name: "Maldivian", code: "MV" },
  { name: "Malian", code: "ML" },
  { name: "Maltese", code: "MT" },
  { name: "Marshallese", code: "MH" },
  { name: "Martinican", code: "MQ" },
  { name: "Mauritanian", code: "MR" },
  { name: "Mauritian", code: "MU" },
  { name: "Mahoran", code: "YT" },
  { name: "Mexican", code: "MX" },
  { name: "Micronesian", code: "FM" },
  { name: "Moldovan", code: "MD" },
  { name: "Monegasque", code: "MC" },
  { name: "Mongolian", code: "MN" },
  { name: "Montserratian", code: "MS" },
  { name: "Moroccan", code: "MA" },
  { name: "Mozambican", code: "MZ" },
  { name: "Burmese", code: "MM" },
  { name: "Namibian", code: "NA" },
  { name: "Nauruan", code: "NR" },
  { name: "Nepali", code: "NP" },
  { name: "Dutch", code: "NL" },
  { name: "Dutch Antillean", code: "AN" },
  { name: "New Caledonian", code: "NC" },
  { name: "New Zealander", code: "NZ" },
  { name: "Nicaraguan", code: "NI" },
  { name: "Nigerien", code: "NE" },
  { name: "Nigerian", code: "NG" },
  { name: "Niuean", code: "NU" },
  { name: "Norfolk Islander", code: "NF" },
  { name: "Northern Mariana Islander", code: "MP" },
  { name: "Norwegian", code: "NO" },
  { name: "Omani", code: "OM" },
  { name: "Pakistani", code: "PK" },
  { name: "Palauan", code: "PW" },
  { name: "Palestinian", code: "PS" },
  { name: "Panamanian", code: "PA" },
  { name: "Papua New Guinean", code: "PG" },
  { name: "Paraguayan", code: "PY" },
  { name: "Peruvian", code: "PE" },
  { name: "Filipino", code: "PH" },
  { name: "Pitcairnese", code: "PN" },
  { name: "Polish", code: "PL" },
  { name: "Portuguese", code: "PT" },
  { name: "Puerto Rican", code: "PR" },
  { name: "Qatari", code: "QA" },
  { name: "Reunionese", code: "RE" },
  { name: "Romanian", code: "RO" },
  { name: "Russian", code: "RU" },
  { name: "Rwandan", code: "RW" },
  { name: "Saint Helenian", code: "SH" },
  { name: "Kittitian/Nevisian", code: "KN" },
  { name: "Saint Lucian", code: "LC" },
  { name: "Saint-Pierrais", code: "PM" },
  { name: "Vincentian", code: "VC" },
  { name: "Samoan", code: "WS" },
  { name: "Sammarinese", code: "SM" },
  { name: "São Tomean", code: "ST" },
  { name: "Saudi", code: "SA" },
  { name: "Senegalese", code: "SN" },
  { name: "Serbian", code: "CS" },
  { name: "Seychellois", code: "SC" },
  { name: "Sierra Leonean", code: "SL" },
  { name: "Singaporean", code: "SG" },
  { name: "Slovak", code: "SK" },
  { name: "Slovenian", code: "SI" },
  { name: "Solomon Islander", code: "SB" },
  { name: "Somali", code: "SO" },
  { name: "South African", code: "ZA" },
  { name: "South Georgian", code: "GS" },
  { name: "Spanish", code: "ES" },
  { name: "Sri Lankan", code: "LK" },
  { name: "Sudanese", code: "SD" },
  { name: "Surinamese", code: "SR" },
  { name: "Svalbardian", code: "SJ" },
  { name: "Swazi", code: "SZ" },
  { name: "Swedish", code: "SE" },
  { name: "Swiss", code: "CH" },
  { name: "Syrian", code: "SY" },
  { name: "Taiwanese", code: "TW" },
  { name: "Tajik", code: "TJ" },
  { name: "Tanzanian", code: "TZ" },
  { name: "Thai", code: "TH" },
  { name: "Timorese", code: "TL" },
  { name: "Togolese", code: "TG" },
  { name: "Tokelauan", code: "TK" },
  { name: "Tongan", code: "TO" },
  { name: "Trinidadian", code: "TT" },
  { name: "Tunisian", code: "TN" },
  { name: "Turkish", code: "TR" },
  { name: "Turkmen", code: "TM" },
  { name: "Turks and Caicos Islander", code: "TC" },
  { name: "Tuvaluan", code: "TV" },
  { name: "Ugandan", code: "UG" },
  { name: "Ukrainian", code: "UA" },
  { name: "Emirati", code: "AE" },
  { name: "British", code: "GB" },
  { name: "American", code: "US" },
  { name: "American", code: "UM" },
  { name: "Uruguayan", code: "UY" },
  { name: "Uzbek", code: "UZ" },
  { name: "Ni-Vanuatu", code: "VU" },
  { name: "Vatican", code: "VA" },
  { name: "Venezuelan", code: "VE" },
  { name: "Vietnamese", code: "VN" },
  { name: "British Virgin Islander", code: "VG" },
  { name: "U.S. Virgin Islander", code: "VI" },
  { name: "Wallisian/Futunan", code: "WF" },
  { name: "Sahrawi", code: "EH" },
  { name: "Yemeni", code: "YE" },
  { name: "Zambian", code: "ZM" },
  { name: "Zimbabwean", code: "ZW" },
];

export default nationalities;
